tile: "T18HYG"
start_date: "2020-09-01"
end_date: "2021-09-01"

n: 60
base_path: "data/processed"
user: "nicolas.isla@ug.uchile.cl"
password: "??"

# T18HYG
# T19HBB
# T18HYF
# T19HBA
# T18HXE
# T18HYE
# T19HBV
# T18HXD
# T18HYD
# T19HBU
# T18HXC
# T18HYC